AllCops:
  Exclude:
    - bin/*

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - class_methods

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 1500

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf
